# Generated by Django 4.2.3 on 2025-10-29 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['-order_date'], name='cart_orderd_order_d_fccd41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order_number'], name='cart_orderd_order_n_22b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['user'], name='cart_orderd_user_id_f8f556_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['status'], name='cart_orderd_status_df61af_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['payment_status'], name='cart_orderd_payment_ea7edd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'service', 'booking_date', 'booking_time')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='cart_cart_user_id_2c8a21_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id', 'status'], name='cart_cart_session_31bbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-last_activity'], name='cart_cart_last_ac_8149bb_idx'),
        ),
    ]
