# Generated by Django 4.2.3 on 2023-09-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='self_id',
            new_name='object_id',
        ),
    ]
