# Generated by Django 4.2.3 on 2023-07-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='number',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='last_used_time',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='null', max_length=256, upload_to='service_images'),
            preserve_default=False,
        ),
    ]
