# Generated by Django 4.2.3 on 2023-09-21 07:33

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar')),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(default=None, max_length=200)),
                ('contacts', models.IntegerField(null=True)),
                ('citizen', models.CharField(default=None, max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='user',
        ),
    ]
